import type { Metadata } from 'next';
import '../globals.css';
import AppProviders from 'AppProvider';
import { roboto } from 'configs/Fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${roboto.variable} scroll-smooth antialiased`}>
      <body>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
